name: issue-to-project
on:
  issues:
    types:
      - opened

env:
  GITHUB_TOKEN: ${{ secrets.ISSUE_TRACKER }}
  PROJECT_OWNER: ElementX-Network # Project の所有者名
  PROJECT_NUMBER: 1               # Project 番号

jobs:
  manage_project:
    runs-on: ubuntu-22.04
    steps:
    - name: Add Issue to Project
      uses: monry/actions-add-issue-to-project@v1
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        project-owner: ${{ env.PROJECT_OWNER }}
        project-number: ${{ env.PROJECT_NUMBER }}
        issue-id: ${{ github.event.issue.node_id }}